apiVersion: v1
kind: Secret
metadata:
  # Tên secret sẽ được lấy từ values.yaml
  name: {{ .Values.appConfig.database.secretName }}
type: Opaque
stringData:
  # Key 'database-url' phải khớp với key trong deployment
  # Giá trị được lấy từ file values.yaml
  database-url: {{ .Values.appConfig.database.connectionString }}