# secrets/platform-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: shared-platform-credentials
  namespace: platform-services # Namespace chúng ta sẽ cài DB và Redis
type: Opaque
stringData:
  # Mật khẩu cho user 'postgres' (admin của DB)
  postgres-password: "YourStrongPostgresAdminPassword"

  # Mật khẩu cho user 'airflow_user'
  airflow-db-password: "YourStrongAirflowPassword"

  # Mật khẩu cho user 'litellm_user'
  litellm-db-password: "YourStrongLiteLLMPassword"

  # Mật khẩu cho Redis
  redis-password: "YourStrongRedisPassword"