# Khai báo các môi trường
environments:
  development:
    values:
    - ./environments/development.yaml

repositories:
  - name: apache-airflow
    url: https://airflow.apache.org
---
# Danh sách các Helm Release cần triển khai
releases:
    # Release 1: Airflow
  - name: airflow-system
    namespace: airflow
    chart: apache-airflow/airflow
    version: 1.16.0
    values:
      - ./deployments/airflow/airflow.yaml # Sử dụng cấu hình chung cho Airflow
    # Release 2: Litellm Service
  - name: litellm-service         # Tên Helm release
    namespace: platform-services      # Namespace đích
    chart: ./deployments/litellm # Đường dẫn đến chart
    values:
      - ./deployments/litellm/litellm.yaml # Sử dụng cấu hình chung cho Litellm Service

  # Release 3: Application (frontend, backend)
  - name: app-services          # Tên Helm release
    namespace: application      # Namespace đích
    chart: ./deployments/application # Đường dẫn đến chart




