# argocd/argocd-values.yaml
repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: cmp-helmfile-plugin
      configMap:
        name: cmp-helmfile-plugin

  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/custom-tools

  initContainers:
    - name: download-tools
      image: alpine:3.18
      # command: ["sh", "-c", "wget https://get.helm.sh/helm-v3.15.2-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /custom-tools/helm && wget https://github.com/helmfile/helmfile/releases/download/v0.165.0/helmfile_0.165.0_linux_amd64.tar.gz -O - | tar -xzO helmfile > /custom-tools/helmfile && chmod +x /custom-tools/helm /custom-tools/helmfile && ln -s /custom-tools/helm /usr/local/bin/helm && ln -s /custom-tools/helmfile /usr/local/bin/helmfile"]
      command: ["sh", "-c", "wget https://get.helm.sh/helm-v3.15.2-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /custom-tools/helm && wget https://github.com/helmfile/helmfile/releases/download/v0.165.0/helmfile_0.165.0_linux_amd64.tar.gz -O - | tar -xzO helmfile > /custom-tools/helmfile && chmod +x /custom-tools/helm /custom-tools/helmfile"]

      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools

  env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/custom-tools

  extraContainers:
    - name: cmp-helmfile
      image: quay.io/argoproj/argocd:v2.11.7
      command: [/var/run/argocd/argocd-cmp-server]
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - name: var-files
          mountPath: /var/run/argocd
        - name: cmp-helmfile-plugin
          mountPath: /home/argocd/cmp-server/config # <-- ĐỊA CHỈ ĐÚNG
        - name: custom-tools
          mountPath: /usr/local/bin/custom-tools
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
      env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/custom-tools


# argocd/argocd-values.yaml

# ... (Phần `configs` và `repoServer` giữ nguyên) ...

# ===================================================================
# PHẦN SERVER - CẤU HÌNH INGRESS HOÀN CHỈNH
# ===================================================================
server:
  # ===================================================================
  # PHẦN INGRESS ĐƯỢC CẤU HÌNH THEO ĐÚNG CẤU TRÚC CHART
  # ===================================================================
  ingress:
    enabled: true
    controller: generic # Giữ là 'generic' để tương thích tốt nhất
    
    # Dùng đúng khóa `hostname`
    hostname: argocd.34.49.177.9.nip.io # <-- Thay bằng IP Ingress mới nhất của bạn
    
    # Bật TLS bằng cờ boolean
    tls: true
    
    # Sử dụng tính năng tích hợp sẵn cho GKE Health Check
    gke:
      backendConfig:
        name: argocd-backend-config
        enabled: true
        spec:
          healthCheck:
            requestPath: /healthz
            port: 8080
            type: HTTPS

  service:
    type: ClusterIP
    ports:
      - port: 443
        targetPort: 8080
        name: https
