{{- if .Values.backend.serviceName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-chart.fullname" . }}-nginx-config
  labels:
    {{- include "frontend-chart.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # React SPA entry point
        location / {
            try_files $uri /index.html;
        }

        # Phục vụ static assets build ra
        location /assets/ {
            try_files $uri =404;
        }

        # (Optional) các file favicon, vite.svg,...
        location ~* \.(svg|ico|png|woff2?)$ {
            try_files $uri =404;
        }

        # Forward API request tới backend
        location /api/ {
            proxy_pass http://{{ .Values.backend.serviceName }}:{{ .Values.backend.servicePort }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
{{- end }}
