# monitoring/prometheus-values.yaml

# ==========================================================
# PHẦN THÊM VÀO ĐỂ SỬA LỖI: Tắt việc cài đặt CRD
# ==========================================================
# Khối này sẽ ra lệnh cho Prometheus Operator trong chart
# không tự mình tạo ra các Custom Resource Definitions.
prometheusOperator:
  createCrds: false
# ==========================================================

# -- Cấu hình chung --
# Các khối này giữ nguyên như cũ
grafana:
  enabled: true
prometheus:
  enabled: true
alertmanager:
  enabled: true

# -- Cấu hình Grafana --
# Có hai khối grafana, đây có thể là lỗi đánh máy, hãy gộp chúng lại.
grafana:
  adminPassword: "YourVeryStrongGrafanaPassword123"
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    storageClassName: standard # Bỏ comment nếu bạn muốn dùng StorageClass cụ thể

# -- Cấu hình Prometheus --
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          # Dung lượng cụ thể sẽ do file môi trường ghi đè
          # requests:
          #   storage: 20Gi
