apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-openai-api-key-sync
  namespace: platform-services # Namespace của LiteLLM
spec:
  secretStoreRef:
    name: gcp-secret-store # Trỏ đến ClusterSecretStore đã tạo
    kind: ClusterSecretStore
  
  target:
    # Tên của Kubernetes Secret sẽ được tạo ra
    name: litellm-api-keys
    # (Tùy chọn) Template để thêm các label/annotation vào K8s Secret
    # template:
    #   metadata:
    #     labels:
    #       app.kubernetes.io/name: "litellm"

  # Dữ liệu cần đồng bộ
  data:
  - secretKey: openai-api-key # Key sẽ được tạo trong K8s Secret
    remoteRef:
      key: litellm-openai-api-key # Tên secret_id trên GCP
      version: "latest" # Luôn lấy phiên bản mới nhất
