# manifests/external-secrets/airflow.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitsync-ssh-key-secret
  namespace: airflow
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore

  target:
    name: gitsync-ssh-key
    template:
      type: Opaque

  data:
    - secretKey: gitSshKey                      # <- FIXED KEY NAME
      remoteRef:
        key: gitsync-ssh-key          # GCP Secret ID


---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # Đặt một cái tên chung cho tất cả secret của Airflow
  name: airflow-all-secrets-sync
  namespace: airflow 
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  
  target:
    # TẤT CẢ các giá trị sẽ được gom vào K8s Secret duy nhất này
    name: airflow-secrets 
    
  # `data` là một danh sách, bạn có thể định nghĩa nhiều mục ở đây
  data:
  # Mục 1: Lấy Fernet Key
  - secretKey: airflow-fernet-key # Key trong K8s Secret
    remoteRef:
      key: airflow-fernet-key # Tên secret_id trên GCP
  # # Mục 2: Lấy UI username từ JSON
  # - secretKey: airflow-ui-username # Key trong K8s Secret
  #   remoteRef:
  #     key: airflow-ui-credentials
  #     property: username # Trích xuất thuộc tính 'username'
      
  # # Mục 3: Lấy UI password từ JSON
  # - secretKey: airflow-ui-password # Key trong K8s Secret
  #   remoteRef:
  #     key: airflow-ui-credentials
  #     property: password # Trích xuất thuộc tính 'password'