# manifests/cluster-secret-store.yaml

apiVersion: external-secrets.io/v1 # Đã sửa ở lần trước
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      # Thay thế bằng thông tin chính xác của bạn
      projectID: "alpine-figure-461007-i9"
      auth:
        workloadIdentity:
          clusterLocation: "asia-southeast1-a"
          clusterName: "simple-cluster" # Tên cluster GKE của bạn
          serviceAccountRef:
            name: eos-ksa
            namespace: "external-secrets"