# airflow/airflow-values.yaml
executor: CeleryExecutor

# Tắt sub-chart postgresql
postgresql:
  enabled: false

# Tắt sub-chart redis
redis:
  enabled: false

# Cấu hình để kết nối đến DB và Redis bên ngoài
externalDatabase:
  type: postgresql
  host: postgresql-shared-postgresql-headless.platform-services.svc.cluster.local
  port: 5432
  database: airflow_db
  user: airflow_user
  passwordSecret: "postgresql-shared-postgresql" # Tên secret do chart Bitnami tạo
  passwordSecretKey: postgres-password # Dùng user `postgres` hoặc tạo secret riêng

externalRedis:
  host: redis-shared-master.platform-services.svc.cluster.local
  port: 6379
  passwordSecret: "redis-shared" # Tên secret do chart Bitnami tạo
  passwordSecretKey: redis-password
  databaseNumber: 0 # Dùng DB 0 cho Airflow