executor: "KubernetesExecutor"

images:
  airflow:
    repository: gcr.io/alpine-figure-461007-i9/custom-airflow
    tag: latest
    pullPolicy: Always


serviceAccount:
  create: true
  name: airflow-ksa
  annotations:
    iam.gke.io/gcp-service-account: airflow-sa-crawl2insight@alpine-figure-461007-i9.iam.gserviceaccount.com


# Gán service account cho từng component
webserver:
  serviceAccount:
    name: airflow-ksa
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
    initialDelaySeconds: 30
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    failureThreshold: 10

scheduler:
  serviceAccount:
    name: airflow-ksa

triggerer:
  serviceAccount:
    name: airflow-ksa

worker:
  serviceAccount:
    name: airflow-ksa
  extraContainers:
    - name: cloud-sql-proxy
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0"
      args:
        - "--structured-logs"
        - "--port=5432"
        - "alpine-figure-461007-i9:asia-southeast1:job-pipeline-db"
      securityContext:
        runAsNonRoot: true

extraPipPackages:
  - dateparser
  - playwright

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: git@github.com:tinhnguyen0110/job-crawl-pipeline.git
    branch: deploy_gke
    subPath: airflow/dags
    depth: 1
    wait: 10
    sshKeySecret: airflow-git-ssh-key
    rev: HEAD

logs:
  persistence:
    enabled: false

config:
  kubernetes:
    delete_worker_pods: "False"
  logging:
    remote_logging: "True"
    remote_base_log_folder: "gs://airflow-logs-tinhnv-gke/logs"
    remote_log_conn_id: "google_cloud_default"

postgresql:
  enabled: true
  persistence:
    accessModes:
      - ReadWriteOnce
