executor: "KubernetesExecutor"

airflow:
  image:
    repository: gcr.io/YOUR_PROJECT_ID/airflow-custom  # <-- thay bằng Docker image của bạn
    tag: latest
    pullPolicy: Always

  config:
    AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
    AIRFLOW__CORE__FERNET_KEY: "YOUR_FERNET_KEY"  # tạo bằng: `python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"`
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://<db_user>:<db_pass>@127.0.0.1:5432/<db_name>
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: Admin
      lastName: User

  extraEnv:
    - name: CLOUD_SQL_INSTANCE
      value: "your-gcp-project:your-region:your-instance-name"
    - name: DB_USER
      value: "<db_user>"
    - name: DB_PASS
      value: "<db_pass>"
    - name: DB_NAME
      value: "<db_name>"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/your-org/your-dags-repo.git"
    branch: "main"
    subPath: ""
    syncInterval: 60
    credentialsSecret: ""  # dùng nếu private repo

webserver:
  service:
    type: LoadBalancer
    port: 8080

logs:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: "standard"

postgresql:
  enabled: false  # ❌ Tắt PostgreSQL tích hợp, bạn đã có Cloud SQL riêng

redis:
  enabled: false  # ❌ Nếu không dùng CeleryExecutor thì không cần Redis

scheduler:
  replicas: 1

workers:
  enabled: false  # KubernetesExecutor không cần worker

triggerer:
  replicas: 1
