executor: "KubernetesExecutor"

image:
  repository: gcr.io/alpine-figure-461007-i9/custom-airflow:v1
  pullPolicy: Always

serviceAccount:
  create: false
  name: airflow-ksa



dags:
  persistence:
      enabled: false # Không cần lưu trữ DAGs trên disk
  gitSync:
    enabled: true
    repo: git@github.com:tinhnguyen0110/job-crawl-pipeline.git
    branch: deploy_gke
    subPath: airflow/dags  # thư mục chứa DAGs trong repo
    depth: 1
    wait: 60
    sshKeySecret: airflow-git-ssh-key
    # sshKnownHosts: |
    #   github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    rev: HEAD


# logs:
#   persistence:
#     enabled: true
#     # Thêm dòng này để chỉ yêu cầu ổ đĩa cho một node duy nhất
#     size: 1Gi
#     storageClassName: "standard"
logs:
  persistence:
    enabled: false

postgresql:
  enabled: true  # ❌ Tắt PostgreSQL tích hợp, bạn đã có Cloud SQL riêng
  persistence:
      # Buộc yêu cầu loại ổ đĩa chỉ cho phép 1 node ghi tại 1 thời điểm
      # Điều này tương thích với StorageClass "standard-rwo" mặc định của GKE
      accessModes:
        - ReadWriteOnce

workers:
  extraContainers:
    - name: cloud-sql-proxy
      image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0"
      command:
        - "/cloud_sql_proxy"
        - "--structured-logs"
        - "-instances=alpine-figure-461007-i9:asia-southeast1:job-pipeline-db=tcp:5432"
      securityContext:
        runAsNonRoot: true

# webserver:
#   extraContainers:
#     - name: cloud-sql-proxy
#       image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0"
#       command:
#         - "/cloud_sql_proxy"
#         - "--structured-logs"
#         - "-instances=alpine-figure-461007-i9:asia-southeast1:job-pipeline-db=tcp:5432"
#       securityContext:
#         runAsNonRoot: true

# scheduler:
#   extraContainers:
#     - name: cloud-sql-proxy
#       image: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0"
#       command:
#         - "/cloud_sql_proxy"
#         - "--structured-logs"
#         - "-instances=alpine-figure-461007-i9:asia-southeast1:job-pipeline-db=tcp:5432"
#       securityContext:
#         runAsNonRoot: true