# values.yaml

# 1. Chỉ định image tùy chỉnh từ Artifact Registry
images:
  repository: a_placeholder_for_image_repository # Sẽ được thay thế bằng lệnh bên dưới
  tag: a_placeholder_for_image_tag             # Sẽ được thay thế bằng lệnh bên dưới

# 2. Chọn Executor
executor: KubernetesExecutor

# 3. Cấu hình DAGs (ví dụ: gitSync)
dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/your-username/your-airflow-dags-repo.git"
    branch: "main"
    # Nếu repo private, bạn cần tạo K8s secret và tham chiếu tại đây
    # credentialsSecret: "git-credentials-secret"

# 4. Cấu hình Webserver Secret Key
webserverSecretKey: "YOUR_GENERATED_WEBSERVER_SECRET_KEY" # Tạo bằng: openssl rand -hex 30

# 5. Cấu hình cơ sở dữ liệu
# Khuyến nghị sử dụng Cloud SQL cho môi trường production thay vì PostgreSQL trong cluster
# Nhưng để đơn giản, ta vẫn dùng PostgreSQL của chart
postgresql:
  enabled: false

# 6. (Nâng cao & Khuyến nghị) Cấu hình Workload Identity
# Giúp các pod Airflow có quyền truy cập các dịch vụ GCP khác (GCS, BigQuery)
# một cách an toàn mà không cần key file.
# Để sử dụng, bạn cần tạo Google Service Account (GSA) và Kubernetes Service Account (KSA)
# và liên kết chúng với nhau.
# Bỏ comment phần dưới nếu bạn đã cấu hình Workload Identity
# serviceAccount:
#   create: true
#   name: "airflow-ksa" 
#   annotations:
#     iam.gke.io/gcp-service-account: "your-gsa-name@${PROJECT_ID}.iam.gserviceaccount.com"