apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-app-monitor
  namespace: application # Namespace của ứng dụng backend
  labels:
    release: prometheus-stack # Label này có thể cần hoặc không, tùy cấu hình
spec:
  selector:
    matchLabels:
      app: my-backend-app # Label của Service đang trỏ tới pod backend
  endpoints:
  - port: http # Tên port trong Service của bạn mà expose endpoint /metrics
    interval: 30s
    path: /metrics