apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-argo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Gán vào wave 0, chạy đầu tiên
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tinhnguyen0110/job-crawl-pipeline.git' # <-- Nhớ thay
    targetRevision: main
    path: '.'
    plugin:
      name: helmfile
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application # <-- THAY ĐỔI
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true