apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm-service # <-- THAY ĐỔI
  namespace: argocd
  annotations:
    # Gán vào wave 0, chạy đầu tiên
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tinhnguyen0110/job-crawl-pipeline.git' # <-- Nhớ thay
    targetRevision: main
    path: '.'
    # Quan trọng: Vẫn dùng plugin helmfile vì airflow được quản lý bởi helmfile
  destination:
    server: 'https://kubernetes.default.svc'
    # Namespace đích cho release này
    namespace: platform-services # <-- THAY ĐỔI
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true