apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-shared
  namespace: argocd
  annotations:
    # Gán vào wave 0, chạy đầu tiên
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: '15.5.18' # Chỉ định một phiên bản cụ thể để ổn định
    helm:
      values: |
        auth:
          # Vẫn dùng existingSecret để đặt mật khẩu cho user admin `postgres`
          existingSecret: "platform-database-credentials"
          secretKeys:
            adminPasswordKey: "postgres-password"

        # Sử dụng script của bạn để khởi tạo các DB và user khác
        primary:
          initdb:
            scripts:
              create_dbs.sql: |
                -- Tạo database
                CREATE DATABASE litellm_db;
                CREATE DATABASE airflow_db;

                -- Tạo user
                CREATE USER litellm_user WITH PASSWORD 'litellm123';
                CREATE USER airflow_user WITH PASSWORD 'airflow123';

                -- Gán quyền sở hữu (cách làm này bao hàm tất cả các quyền cần thiết)
                ALTER DATABASE litellm_db OWNER TO litellm_user;
                ALTER DATABASE airflow_db OWNER TO airflow_user;
          
            persistence:
              # Dung lượng nhỏ cho môi trường dev
              size: 8Gi
  destination:
    server: 'https://kubernetes.default.svc'
    # Triển khai database vào namespace chung cho các dịch vụ nền tảng
    namespace: platform-services
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]