apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    # Chạy ở Wave 0, cùng lúc với các nền tảng stateful khác
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tinhnguyen0110/job-crawl-pipeline.git' # <-- URL Repo của bạn
    targetRevision: main
    path: '.'
    plugin:
      name: helmfile
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: 
      - ServerSideApply=true
      - CreateNamespace=true