apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: redis
    targetRevision: '19.6.3'
    helm:
      values: |
        auth:
          enabled: true
          # ==========================================================
          # THAY ĐỔI Ở ĐÂY:
          # Thay vì `password`, chúng ta dùng `existingSecret`.
          # ==========================================================
          existingSecret: "platform-database-credentials" # <-- Tên Secret chung của chúng ta

          # Chỉ cho chart biết key nào trong secret chứa mật khẩu Redis
          existingSecretPasswordKey: "redis-password"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: platform-services
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]