# .github/actions/setup-docker/action.yaml
name: "Setup Docker for GAR"
description: "Setup Docker Buildx and configure auth for Artifact Registry"
inputs:
  gar_location:
    required: true
    description: "GCP Artifact Registry region"
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ inputs.gar_location }}-docker.pkg.dev
      shell: bash