{{- /* Kiểm tra xem có nên tạo Service Account hay không */ -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gsaEmail }}
  labels:
    {{- /* Include các labels chuẩn từ file _helpers.tpl */ -}}
    {{- include "backend-chart.labels" . | nindent 4 }}
{{- end -}}