# deployments/common/platform-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  # Đặt một cái tên rõ ràng
  name: platform-database-credentials
  namespace: platform-services
type: Opaque
stringData:
  # Mật khẩu cho user admin của PostgreSQL
  litellm-db-username: "litellm_user"
  postgres-password: "YourAdminPassword123"
  # Mật khẩu riêng cho user của LiteLLM
  litellm-db-password: "litellm123"
  airflow-db-password: "airflow123"
  redis-password: "YourStrongRedisPassword123" 