name: "Setup GCP Auth + Docker Buildx + Configure GAR"
description: "Authenticate to GCP, setup Docker Buildx and configure Artifact Registry"

runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

    - name: Set up Docker Buildx (with docker-container)
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Create and use builder
      run: |
        docker buildx create --name mybuilder --driver docker-container --use || true
        docker buildx inspect --bootstrap
      shell: bash

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev
      shell: bash
